FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /project

RUN apt-get update && apt-get install -y \
valgrind \
libreadline-dev \
nano \
lldb \
build-essential \
sudo \
curl \
ncurses-base \
wget \
git
